version: '3.9'

x-common-test-config: &common-test-config
  build:
    context: ../
    dockerfile: deployment/docker/Dockerfile
    target: prod
  volumes:
    - ../django_project:/home/web/django_project
    - ./volumes/static:/home/web/static
    - ./volumes/media:/home/web/media

services:

  worker:
    <<: *common-test-config

  celery_beat:
    <<: *common-test-config

  django:
    <<: *common-test-config
    command: >
      sh -c "
      echo 'Running Tests...';
      python manage.py test
      "
