# Generated by Django 5.1.7 on 2025-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_monitoringindicatortype_scheduledtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataSource',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_url', models.URLField(help_text='API Endpoint URL')),
                ('requires_auth',
                 models.BooleanField(default=False,
                                     help_text='If true, authentication is required')),
                ('auth_token',
                 models.CharField(blank=True,
                                  help_text='API authentication token (if required)',
                                  max_length=512,
                                  null=True)),
                ('request_method',
                 models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')],
                                  default='GET',
                                  help_text='HTTP request method for the API',
                                  max_length=10)),
                ('response_format',
                 models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML'), ('CSV', 'CSV'),
                                           ('GeoTIFF', 'GeoTIFF')],
                                  default='JSON',
                                  help_text='Format of the response data',
                                  max_length=10)),
                ('additional_params',
                 models.JSONField(blank=True, help_text='Extra parameters for API calls',
                                  null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
