# Generated by Django 5.1.7 on 2025-03-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_externaldatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldatasource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
