# Generated by Django 5.1.7 on 2025-03-19 07:24

import django.db.models.deletion
import project.models.monitor
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    ScheduledTask = apps.get_model('project', 'ScheduledTask')
    for task in ScheduledTask.objects.all():
        task.uuid = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0003_externaldatasource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='id',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   editable=False,
                                   primary_key=True,
                                   serialize=False),
        ),
        migrations.RunPython(generate_uuids, lambda a, b: None),
        migrations.AlterField(
            model_name='externaldatasource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'),
                                            ('completed', 'Completed'), ('failed', 'Failed')],
                                   default='pending',
                                   max_length=25),
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('uuid',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('status',
                 models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'),
                                           ('completed', 'Completed'), ('failed', 'Failed')],
                                  default='pending',
                                  max_length=25)),
                ('parameters', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskOutput',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.monitor.output_layer_dir_path)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
                ('monitoring_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='project.monitoringindicatortype')),
                ('task',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='task_outputs',
                                   to='project.analysistask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('uuid',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('log', models.TextField()),
                ('level', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=36)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['content_type', 'object_id'],
                                 name='project_tas_content_b8874f_idx')
                ],
            },
        ),
    ]
