# Generated by Django 5.1.7 on 2025-03-18 06:28

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    ScheduledTask = apps.get_model('project', 'ScheduledTask')
    for task in ScheduledTask.objects.all():
        task.uuid = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_externaldatasource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='id',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunPython(generate_uuids, lambda a, b: None),
        migrations.AlterField(
            model_name='externaldatasource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=25),
        ),
    ]
