# Generated by Django 5.1.7 on 2025-03-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_scheduledtask_id_scheduledtask_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='celery_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
