# Generated by Django 5.1.7 on 2025-03-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_externaldatasource_name'),
        ('project', '0005_analysistask_celery_task_id'),
    ]

    operations = [
    ]
