# Generated by Django 5.1.7 on 2025-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_crawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoutput',
            name='analysis_date',
            field=models.DateField(blank=True, help_text='Date when the analysis was taken', null=True),
        ),
        migrations.AddField(
            model_name='taskoutput',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
