# Generated by Django 5.1.7 on 2025-03-28 10:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_taskoutput_analysis_date_taskoutput_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoutput',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
