# Generated by Django 5.1.7 on 2025-04-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_taskoutput_bbox_taskoutput_observation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='resolution',
            field=models.IntegerField(default=20),
        ),
    ]
