# Generated by Django 5.1.7 on 2025-04-21 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_crawler_bbox_alter_crawler_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_to_process', models.IntegerField(default=0)),
                ('processed_data', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.crawler')),
            ],
        ),
    ]
