# Generated by Django 5.1.7 on 2025-06-18 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_crawlprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoutput',
            name='is_mosaic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskoutput',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_outputs', to='project.analysistask'),
        ),
    ]
