# Generated by Django 5.1.7 on 2025-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awei_threshold', models.FloatField(blank=True, default=-0.11, help_text='AWEI threshold value to detect water body. Anything above this will be considered as water body.', null=True)),
                ('water_body_min_pixel', models.IntegerField(blank=True, default=100, help_text='Minimum number of pixels to consider as water body.', null=True)),
            ],
        ),
    ]
