name: 📖 Build MkDocs and Swagger UI and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "**.md"
      - "**.py"
      - "docs/**"
      - "assets/**"
      - "swagger.html"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "**.md"
      - "**.py"
      - "docs/**"
      - "assets/**"
      - "swagger.html"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build Docs + Swagger
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    steps:
      - name: Checkout main from GitHub
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: timlinux/pip-action@v1
        with:
          packages: |
            mkdocs-material
            mkdocs-video
            mkdocstrings[python]
            qrcode

      - name: Create MkDocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh

      - name: Build MkDocs site
        run: |
          mkdocs build --config-file docs/mkdocs.yml --site-dir site/docs

      - name: Copy Swagger HTML to site root
        run: |
          mkdir -p site
          cp swagger.html site/index.html

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  test-pr:
    name: Test Docs Build on PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: timlinux/pip-action@v1
        with:
          packages: |
            mkdocs-material
            mkdocs-video
            mkdocstrings[python]
            qrcode

      - name: Create MkDocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh

      - name: Build MkDocs site (no deploy)
        run: |
          mkdocs build --config-file docs/mkdocs.yml --site-dir site/docs
