name: Django Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build and Test via Docker Compose
        run: |
          # Move into deployment folder if needed
          cd deployment

          # Copy environment
          cp .template.env .env

          # Build images
          docker compose -f docker-compose.yml -f docker-compose.test.yml build

          docker compose -f docker-compose.yml -f docker-compose.test.yml up -d db redis

          docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm django python manage.py test

          # Clean up
          docker compose -f docker-compose.yml -f docker-compose.test.yml down
